"""
Simulation for zebrafish segmentation
Copyright (C) 2016 Ahmet Ay, Carlton Yang

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

_cuda_builder = Builder(
    action = '/usr/local/cuda/bin/nvcc -c -ccbin=g++ -arch=sm_35 $CPPFLAGS $SOURCES -o $TARGET',
    suffix = '.o',
    src_suffix = '.cu')
compile_flags = '-I /usr/local/cuda/include'
link_flags = ''
if ARGUMENTS.get('profiling', 0):
	compile_flags += '-pg'
	link_flags += '-pg'
elif ARGUMENTS.get('debug', 0):
	compile_flags += ' -g'
	link_flags += ' -g'
elif ARGUMENTS.get('memtrack', 0):
	compile_flags += '-D MEMTRACK'

env = Environment(CXX='g++', BUILDERS={'NVCC' : _cuda_builder})
env.Append(CPPFLAGS=compile_flags, LIBPATH='-L/usr/local/cuda/lib64', LIBS=['cudart_static', 'cuda', 'dl', 'pthread', 'rt'], LINKFLAGS=link_flags)
env.NVCC('source/sim')
env.Program(target='simulation', source=['source/main.cpp', 'source/init.cpp', 'source/sim.o', 'source/feats.cpp', 'source/tests.cpp', 'source/io.cpp', 'source/debug.cpp'])
